[package]
name = "cnes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
bitflags = "1.3"
sdl2 = "0.35"
rand = "0.8.4"
log = "0.4.0"
env_logger = "0.9.0"
ringbuf = "0.3.2"